services:
  redis:
    image: redis:7-alpine
    container_name: data-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
    networks:
      - data-network

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: data-prometheus
    restart: always
    volumes:
      - ./prometheus-grafana/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - data-network

  grafana:
    image: grafana/grafana:11.5.2
    container_name: data-grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - data-network

networks:
  data-network:
    driver: bridge

volumes:
  redis-data:
  prometheus-data:
  grafana-data:
