services:
  data-prometheus:
    image: prom/prometheus:v3.2.1
    container_name: data-prometheus
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus-grafana/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring-network

  data-grafana:
    image: grafana/grafana:11.5.2
    container_name: data-grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./prometheus-grafana/grafana/provisioning:/etc/grafana/provisioning
      - ./prometheus-grafana/grafana/dashboards:/var/lib/grafana/dashboards:ro # 읽기 전용 마운트
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
