spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      ssl:
        enabled: false
      key:
        prefix: "redis://"

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false

payment:
  secret-key: ${PAYMENT_SECRET_KEY}
  base-url: https://api.tosspayments.com
  confirm-endpoint: /v1/payments/confirm
  cancel-endpoint: /v1/payments/%s/cancel

logging:
  file:
    name: logs/test.log
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.springframework.orm.jpa: ERROR

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000 # 1H
  refresh-token-validity: 604800000 # 7D

server:
  tomcat:
    mbeanregistry:
      enabled: true
    max-connections: 5000
    accept-count: 500
    connection-timeout: 30000

management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: trainus
      role: api
