global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    monitor: 'trainus-monitor'

scrape_configs:
  # 프로메테우스 자기 자신 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 로컬 개발 환경
  - job_name: 'spring-boot-app-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082', 'host.docker.internal:8083']
        labels:
          env: 'local'

  # 독립 API 서버 수집
  - job_name: 'trainus-independent-api'
    metrics_path: '/actuator/prometheus'
    ec2_sd_configs:
      - region: ap-northeast-2
        port: 8082
    relabel_configs:
      # 'Name' 태그가 'TrainUs-Independent-Api'로 시작하는 인스턴스
      - source_labels: [__meta_ec2_tag_Name]
        regex: TrainUs-Independent-Api.*
        action: keep

      # 그라파나 대시보드용 라벨 추가
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - target_label: env
        replacement: 'baseline'
      - target_label: role
        replacement: 'api'

  # API 서버 수집
  - job_name: 'trainus-api-apps'
    metrics_path: '/actuator/prometheus'
    ec2_sd_configs:
      - region: ap-northeast-2
        port: 8082
    relabel_configs:
      # 'Name' 태그가 'TrainUs-Api'로 시작하는 인스턴스
      - source_labels: [__meta_ec2_tag_Name]
        regex: TrainUs-Api.*
        action: keep

        # 그라파나 대시보드용 라벨 추가
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - target_label: env
        replacement: 'production'
      - target_label: role
        replacement: 'api'

  # Consumer 서버 수집
  - job_name: 'trainus-consumer-apps'
    metrics_path: '/actuator/prometheus'
    ec2_sd_configs:
      - region: ap-northeast-2
        port: 8083
    relabel_configs:
      # 'Name' 태그가 'TrainUs-Consumer'로 시작하는 인스턴스
      - source_labels: [__meta_ec2_tag_Name]
        regex: TrainUs-Consumer.*
        action: keep
      
      # 그라파나 대시보드용 라벨 추가
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - target_label: env
        replacement: 'production'
      - target_label: role
        replacement: 'consumer'
